#cloud-config

write_files:
  - path: /etc/tenminutevpn/tenminutevpn.yaml
    permissions: "0644"
    owner: root:root
    content: |
      ---
      kind: squid/v1
      metadata:
        name: squid-1
        annotations:
          tenminutevpn.com/config-dir: /etc/squid/
      spec:
        port: 3129
      ---
      kind: wireguard/v1
      metadata:
        name: wireguard-1
        annotations:
          tenminutevpn.com/config-dir: /etc/wireguard/
          tenminutevpn.com/peer-config-dir: /etc/wireguard/peers/
      spec:
        device: wg0
        address: 100.96.0.1/24
        port: 51821
        dns:
          - 1.1.1.1
          - 1.0.0.1
        peers:
          - allowedips:
              - 100.96.0.5/32

runcmd:
  - ["tenminutevpn-manager", "config"]
